### ISSUE TITLE
Wax Search Derivative

### ISSUE THREAD

**Issue by egpalazzolo** [lxcprojects/keywords#1]
While the image and pages functions have run near seamlessly for us on Wax, for some reason the Search isn't working. Would be great to sort that out at some point!

**Comment by jabrah** [comment]
I was able to get search working locally, you'll need to run a task to generate the search index file:

`bundle exec rake wax:search main`

This will generate an `index.json` file in the `search/` folder. This will need to be committed to GitHub to get search working in the GH Pages site.
