### ISSUE TITLE
Thumbnails

### ISSUE THREAD

**Issue by egpalazzolo** [lxcprojects/keywords#13]
Two main issues at this time:
1) The thumbnail images that come up when you click any of the Keywords on the "By Keyword" page are all very narrow and do not show the full document.
2) How/where to change or remove the sub-text that appears underneath the image that currently reads "A from ()" on all of them? Replacing this with the date seems optimal, but we haven't talked about it yet.

**Comment by jabrah** [comment]
Example: http://localhost:4000/keywords/pages/docs_by/keywords/coartacion

**Comment by jabrah** [comment]
Re No2 (sub-text for each card)
What info do you want to show for the caption? We can easily draw from the data in `_keywords/<work>.md` (example https://github.com/lxcprojects/keywords/blob/main/_keywords/d0005.md?plain=1). Note that this would display on all pages that uses this gallery such as the `/documents` and the `docs_by` pages.

For example, as before we have the `label` as the card title and now the `comments` as the caption text:

![image](https://github.com/lxcprojects/keywords/assets/5167587/50bebf71-d8a9-477d-9103-e50fbc758d67)
