### ISSUE TITLE
Openseadragon reference strip thumbnails broken

### ISSUE THREAD

**Issue by jabrah** [lxcprojects/keywords#18]
Thumbnails used in the reference strip at the bottom of the Openseadragon viewer when multiple pages are involved do not show. Looks like OSD is requesting resolutions of these images that don't exist.

The images have a defined IIIF Image (2.0) `info.json` that specify exact sizes, but OSD is requesting resolutions outside of the sizes listed. It's requesting 285px width images, where we only have 250px (and full size) available. Possibly from OSD requesting original width divided by one of the scale factors (`1140 / 4`)

**Comment by jabrah** [comment]
It doesn't seem like there's a simple fix to this issue. There's been an open ticket with OpenSeadragon about this since 2014 and while it's been brought up many times, no fix has been put in place.

* Updating OSD had the same bug
* UniversalViewer, another IIIF viewer has the exact same issue
* Mirador seems to work fine, but has a very large JS bundle size of 2MB, but may not allow zooming past native resolution
  * OpenSeadragon: ~200KB
  * UniversalViewer: ~160KB

**Comment by jabrah** [comment]
Looks like this has been a known issue with UV since around the same time the issue cropped up with OSD. Still unresolved :(

**Comment by jabrah** [comment]
The Wax demo site has OSD working with similar-ish data, should look into why it works there, but not with our data: https://minicomp.github.io/wax/qatar/obj12/

**Comment by egpalazzolo** [comment]
Thanks for looking into all this! I do hesitate to jump to Mirador given the size increase and potential disadvantage of the Zoom being not great. So strange that the demo site works but other OSD stuff is off. I wonder if, given how close we are the the workshop, just getting rid of that OSD bar and having the arrows to change image pages might be one option?
