### ISSUE TITLE
Liquid code for _includes folder with Markdown file for transcription and translation

### ISSUE THREAD

**Issue by egpalazzolo** [lxcprojects/keywords#2]
A few weeks ago, Alex showed us how to use a piece of liquid code to add markdown files from the separate _includes/excerpts folder to the keywords_item.html formatting page. We borrowed the code from his "Frontlines Nurses" project (https://github.com/elotroalex/frontlines/blob/main/_layouts/generic_collection_item.html). I think that maybe it's just a question of surrounding HTML? But we'd like to find a way to get those Markdown files of the transcription and translation added to the individual pages.

**Comment by jabrah** [comment]
I drew up a quick demo copying the excerpts example in the Frontlines project in my local copy of the Keywords project and it seemed to work! You can see how I added it to the `_layouts/generic_collection_item.html`: https://github.com/jabrah/keywords/blob/demo/page-excerpts/_layouts/generic_collection_item.html#L66-L69 (just a demo, this code is not in the project GH)

Here's what that demo code looks like on the page, including the bottom part of the image viewer, the metadata, and the top part of the excerpt. I also spot checked a couple of other pages and they seemed to pull the correct excerpts for those pages too.

![image](https://user-images.githubusercontent.com/5167587/226468770-06e5c9a3-e3ab-4b0a-9fb7-2cbd7f419448.png)

More work could definitely be done to get it integrated more nicely with the rest of the page, but that's easier to iterate on with the excerpts rendering.
