### ISSUE TITLE
Markdown rendering on transcriptions and translations

### ISSUE THREAD

**Issue by egpalazzolo** [lxcprojects/keywords#23]
It looks really messed up and I'm not sure how to fix it for some of the docs: 

- Mama Comba's Gombeaux (most messed up and most important)
- Rights of a Black Man?
- Catherina’s Value
- Apollon, Tinsmith, Makes a Journey

**Comment by jabrah** [comment]
These should be fixed now. The `class="row"` was messing up the widths of each element a bit
