### ISSUE TITLE
Citation

### ISSUE THREAD

**Issue by egpalazzolo** [lxcprojects/keywords#57]
I'm also thinking about how we want to have our citation "generated" on the site for the docs/transcriptions and translations...I'm thinking it might be most convenient to just have it as a facet, but I wonder if there are alternatives that would make it possible to download in different formats (i.e. CMS, MLA, APA, etc.)...

**Comment by jabrah** [comment]
This could likely be done by the site through some javascript, but IMO the most straightforward way to do this would be to fill in citations as columns in the CSV

**Comment by egpalazzolo** [comment]
Add to CSV. For Italics, using Markdown. It works!
