### ISSUE TITLE
Formatting Links

### ISSUE THREAD

**Issue by egpalazzolo** [lxcprojects/keywords#67]
I tried reconfiguring the "keywords_item.html" to add the links to the PDFs (about 6 of which have also been added to GitHub) which are in the CSV as pdf_location, but they aren't showing up!

This was my initial approach:
  - label: 'Transcription and Translation PDF (for Download)'
    value: page.pdf_location
    type: link

(This is also what we'll try to turn into a custom button in the longer term)

**Comment by jabrah** [comment]
For these links, I'd recommend having the `pdf_location` data in the CSV just be the URL, as opposed to a Markdown link. I also don't see any PDFs in the `assets/` folder, so they wouldn't the links would be broken when/if they appeared on the pages
